# Generated by Django 4.2.7 on 2023-11-29 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAvailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('leave_type', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('debit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('coff', models.PositiveIntegerField()),
                ('el', models.PositiveIntegerField()),
                ('lwp', models.PositiveIntegerField()),
                ('rh', models.PositiveIntegerField()),
                ('sl', models.PositiveIntegerField()),
                ('wfh', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CombinedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_availed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_data', to='leave_management.leaveavailed')),
                ('leave_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_data', to='leave_management.leavebalance')),
            ],
        ),
    ]
