# Generated by Django 4.2.7 on 2023-11-29 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_alter_leavebalance_sl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='rh',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
