# Generated by Django 4.2.7 on 2023-11-30 03:28

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_alter_leavebalance_coff_alter_leavebalance_el_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combineddata',
            name='action',
            field=models.CharField(default='Leave Availed', max_length=50),
        ),
        migrations.AddField(
            model_name='combineddata',
            name='coff',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='combineddata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='combineddata',
            name='debit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='combineddata',
            name='el',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='combineddata',
            name='leave_type',
            field=models.CharField(default='Sl', max_length=50),
        ),
        migrations.AddField(
            model_name='combineddata',
            name='lwp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='combineddata',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='combineddata',
            name='region',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combineddata',
            name='rh',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='combineddata',
            name='sl',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='combineddata',
            name='wfh',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
