# Generated by Django 4.2.7 on 2023-11-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0006_combineddata_action_combineddata_coff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CombinedData',
        ),
    ]
